# Terraform Provider testing workflow.
name: Tests

# This GitHub action runs your tests for each pull request and push.
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  # Ensure project builds before running testing matrix
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Format code
        run: make fmt
      - name: Verify code formatting
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after formatting. Run 'make fmt' command and commit."; exit 1)
      - name: Run linters
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
        with:
          version: latest
  generate:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          cache: true
      # We need the latest version of Terraform for our documentation generation to use
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_wrapper: false
      - name: Generate docs
        run: make generate
      - name: Verify docs
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after docs generation. Run 'make generate' command and commit."; exit 1)

  # Run acceptance tests in sequence for each supported Terraform CLI versions
  test_1_0:
    name: Terraform Provider Acceptance Tests v1.0.*
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: '1.0.*'
          terraform_wrapper: false
      - run: go mod download
      - env:
          ABION_API_KEY: ${{ secrets.ABION_API_KEY }}
          ABION_API_HOST: ${{ vars.ABION_API_HOST }}
        run: make testacc
        timeout-minutes: 20
  test_1_1:
    name: Terraform Provider Acceptance Tests v1.1.*
    needs: test_1_0
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: '1.1.*'
          terraform_wrapper: false
      - run: go mod download
      - env:
          ABION_API_KEY: ${{ secrets.ABION_API_KEY }}
          ABION_API_HOST: ${{ vars.ABION_API_HOST }}
        run: make testacc
        timeout-minutes: 20
  test_1_2:
    name: Terraform Provider Acceptance Tests v1.2.*
    needs: test_1_1
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: '1.2.*'
          terraform_wrapper: false
      - run: go mod download
      - env:
          ABION_API_KEY: ${{ secrets.ABION_API_KEY }}
          ABION_API_HOST: ${{ vars.ABION_API_HOST }}
        run: make testacc
        timeout-minutes: 20
  test_1_3:
    name: Terraform Provider Acceptance Tests v1.3.*
    needs: test_1_2
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: '1.3.*'
          terraform_wrapper: false
      - run: go mod download
      - env:
          ABION_API_KEY: ${{ secrets.ABION_API_KEY }}
          ABION_API_HOST: ${{ vars.ABION_API_HOST }}
        run: make testacc
        timeout-minutes: 20
  test_1_4:
    name: Terraform Provider Acceptance Tests v1.4.*
    needs: test_1_3
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: '1.4.*'
          terraform_wrapper: false
      - run: go mod download
      - env:
          ABION_API_KEY: ${{ secrets.ABION_API_KEY }}
          ABION_API_HOST: ${{ vars.ABION_API_HOST }}
        run: make testacc
        timeout-minutes: 20
  test_1_5:
    name: Terraform Provider Acceptance Tests v1.5.*
    needs: test_1_4
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: '1.5.*'
          terraform_wrapper: false
      - run: go mod download
      - env:
          ABION_API_KEY: ${{ secrets.ABION_API_KEY }}
          ABION_API_HOST: ${{ vars.ABION_API_HOST }}
        run: make testacc
        timeout-minutes: 20
