# Terraform Provider testing workflow.
name: Tests

# This GitHub action runs your tests for each pull request.
on:
  pull_request:
    paths-ignore:
      - 'README.md'

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  # Ensure project builds before running testing matrix
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Format code
        run: make fmt
      - name: Verify code formatting
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after formatting. Run 'make fmt' command and commit."; exit 1)
      - name: Run linters
        uses: golangci/golangci-lint-action@ec5d18412c0aeab7936cb16880d708ba2a64e1ae # v6.2.0
        with:
          version: latest
  generate:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      # We need the latest version of Terraform for our documentation generation to use
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_wrapper: false
      - name: Generate docs
        run: make generate
      - name: Verify docs
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after docs generation. Run 'make generate' command and commit."; exit 1)

  # Run acceptance tests in sequence for each supported Terraform CLI versions
  test_1_5:
    name: Terraform Provider Acceptance Tests v1.5.*
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: '1.5.*'
          terraform_wrapper: false
      - run: go mod download
      - env:
          ABION_API_KEY: ${{ secrets.ABION_API_KEY }}
          ABION_API_HOST: ${{ vars.ABION_API_HOST }}
        run: make testacc
        timeout-minutes: 20
  test_1_6:
    name: Terraform Provider Acceptance Tests v1.6.*
    needs: test_1_5
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: '1.6.*'
          terraform_wrapper: false
      - run: go mod download
      - env:
          ABION_API_KEY: ${{ secrets.ABION_API_KEY }}
          ABION_API_HOST: ${{ vars.ABION_API_HOST }}
        run: make testacc
        timeout-minutes: 20
  test_1_7:
    name: Terraform Provider Acceptance Tests v1.7.*
    needs: test_1_6
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: '1.7.*'
          terraform_wrapper: false
      - run: go mod download
      - env:
          ABION_API_KEY: ${{ secrets.ABION_API_KEY }}
          ABION_API_HOST: ${{ vars.ABION_API_HOST }}
        run: make testacc
        timeout-minutes: 20
  test_1_8:
    name: Terraform Provider Acceptance Tests v1.8.*
    needs: test_1_7
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: '1.8.*'
          terraform_wrapper: false
      - run: go mod download
      - env:
          ABION_API_KEY: ${{ secrets.ABION_API_KEY }}
          ABION_API_HOST: ${{ vars.ABION_API_HOST }}
        run: make testacc
        timeout-minutes: 20
  test_1_9:
    name: Terraform Provider Acceptance Tests v1.9.*
    needs: test_1_8
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: '1.9.*'
          terraform_wrapper: false
      - run: go mod download
      - env:
          ABION_API_KEY: ${{ secrets.ABION_API_KEY }}
          ABION_API_HOST: ${{ vars.ABION_API_HOST }}
        run: make testacc
        timeout-minutes: 20
  test_1_10:
    name: Terraform Provider Acceptance Tests v1.10.*
    needs: test_1_9
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: '1.10.*'
          terraform_wrapper: false
      - run: go mod download
      - env:
          ABION_API_KEY: ${{ secrets.ABION_API_KEY }}
          ABION_API_HOST: ${{ vars.ABION_API_HOST }}
        run: make testacc
        timeout-minutes: 20
